### ISSUE TITLE
value ~> is not a member of akka.stream.scaladsl.Source[Int, akka.NotUsed]

### ISSUE THREAD

**Issue by thinkrapido** [typesafehub/activator-akka-stream-scala#41]
https://github.com/typesafehub/activator-akka-stream-scala/blob/master/src/main/scala/sample/stream/WritePrimes.scala

at line 47 and 48 I have this error
value ~> is not a member of akka.stream.scaladsl.Source[Int, akka.NotUsed]

**Comment by ktoso** [comment]
It works.
Make sure you didn't delete the line:
import GraphDSL.Implicits._


-- 
Konrad `ktoso` Malawski
Akka <http://akka.io> @ Lightbend <http://lightbend.com>

On 13 January 2017 at 05:40:23, Romeo Disca (notifications@github.com)
wrote:

https://github.com/typesafehub/activator-akka-stream-scala/blob/master/src/main/scala/sample/stream/WritePrimes.scala

at line 47 and 48 I have this error
value ~> is not a member of akka.stream.scaladsl.Source[Int, akka.NotUsed]

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/typesafehub/activator-akka-stream-scala/issues/41>, or mute
the thread

**Comment by thinkrapido** [comment]
I see
